Update About Page
Crazy-Marvin/Halma pull request #80
Opened 2023-12-31 03:48 UTC by dallasGeorge

hey, i am sadly unable to test the code due to technical issues with my computer but i hope this sets the ground and its a good merge for the development branch. Not sure about the links to terms of service and privacy policy but for now those were the closest i could find.

2023-12-31 22:03 UTC, CrazyMarvin commented on core/src/app/halma/AboutScreen.java
> +    Label helpWIthTranslation;
Here is a typo: helpWIthTranslation --> helpWithTranslation

2023-12-31 22:05 UTC, CrazyMarvin commented
Thank you so much for this PR!

2023-12-31 22:07 UTC, CrazyMarvin commented on core/src/app/halma/AboutScreen.java
> +            link = "https://github.com/Crazy-Marvin/Halma/blob/trunk/.github/CONTACT.md";
This is the link to the Privacy Policy: https://app.getterms.io/view/7FsFk/privacy/en-us

2023-12-31 22:08 UTC, CrazyMarvin commented on core/src/app/halma/AboutScreen.java
> +        if (a == termsOfService)
I thought about Terms of Service and came to the conclusion that they are not needed. Please remove them.
Sorry for the confusion.

2023-12-31 22:09 UTC, CrazyMarvin requested changes
Please check my comments

2024-01-01 04:03 UTC, dallasGeorge commented
Hey I just fixed the code so it matches with all your comments. I hope everything is ok now and happy new year!

2024-01-01 15:44 UTC, merged